# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from datetime import datetime

import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets

import translator_resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1235, 848)
        MainWindow.resize(1235, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: white;")

        self.current_row = -1

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/imgs/WtSmall3.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setStyleSheet("border: 0;\n"
"border-bottom: 3px solid #3273e8;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_8, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 1)
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setStyleSheet("border: 2px solid rgba(0, 0, 0, 0.2);\n"
"border-radius:8px;\n")
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.top_frame)
        self.frame_4.setStyleSheet("border:0;\n"
"border-bottom: 3px solid #3273e8;\n"
"border-radius: 0;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #3273e8;\n"
"border: 0px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.top_frame)
        self.frame_2.setStyleSheet("border:0;\n"
"border-radius:0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(450, 200))
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.top_frame)
        self.frame_5.setStyleSheet("border:0;\n"
"border-bottom: 3px solid #3273e8;\n"
"border-radius:0;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(305, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #3273e8;\n"
"border: 0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.top_frame)
        self.frame_3.setStyleSheet("background-color: #f5f5f5;\n"
"border-radius: 0;\n"
"border:0;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"  border: 1px solid #ebebeb;\n"
"background-color: #ebebeb;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/imgs/pen-tip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton:hover\n"
"{\n"
"  border: 1px solid #ebebeb;\n"
"background-color: #ebebeb;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/imgs/check-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_6, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        self.gridLayout_7.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_6.addWidget(self.top_frame, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Signal handeling
        self.lineEdit.editingFinished.connect(self.numberEntered)
        self.pushButton.clicked.connect(self.editClicked)
        self.pushButton_2.clicked.connect(self.ConfirmClicked)


    def numberEntered(self):
        if(self.lineEdit.text().isnumeric()):
            row_number = int(self.lineEdit.text())
            if row_number < df.shape[0]:
                self.current_row = row_number
                print("current_row = ", self.current_row)

                persian_string_list = df['persian_gloss'].iloc[[row_number]].tolist()
                english_string_list = df['gloss'].iloc[[row_number]].tolist()
    
                english_string = english_string_list[0]
                persian_string = persian_string_list[0]
                
                self.textBrowser.clear()
                self.textBrowser.setTextColor(QtGui.QColor(0, 0, 0))
                self.textBrowser.setFontPointSize(15)
                self.textBrowser.append(english_string)

                self.textEdit.clear()
                self.textEdit.setFontPointSize(15)
                self.textEdit.setReadOnly(True)
                self.textEdit.setTextColor(QtGui.QColor(64, 64, 64))
                self.textEdit.append(persian_string)

            else:
                self.textBrowser.clear()
                self.textBrowser.setTextColor(QtGui.QColor(255, 0, 0))
                self.textBrowser.append("Invalid input. The input in bigger than size of the dataset")


    def editClicked(self):
        if(self.textEdit.isReadOnly):
            current_text = self.textEdit.toPlainText()
            if current_text != "":
                self.textEdit.setReadOnly(False)
                self.textEdit.setTextColor(QtGui.QColor(0, 0, 0))


    def ConfirmClicked(self):
        if(not self.textEdit.isReadOnly()):
            print("enterd the first if")
            current_text = self.textEdit.toPlainText()
            if current_text != "":
                print("enterd the second if")
                df.loc[self.current_row, 'persian_gloss'] = current_text
            df.loc[self.current_row, 'checked'] = 1
            print("confirmed")
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextColor(QtGui.QColor(64, 64, 64))

        print("current row = ", self.current_row)
        print(df['persian_gloss'][self.current_row])
        print(df['checked'][self.current_row])


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Assignment 6 - group 5", "Assignment 6 - group 5"))
        self.label_4.setText(_translate("MainWindow", "Enter the sentence number:"))
        self.label_2.setText(_translate("MainWindow", "English"))
        self.label.setText(_translate("MainWindow", "Persian"))
        self.pushButton.setText(_translate("MainWindow", "Edit"))
        self.pushButton_2.setText(_translate("MainWindow", "Confirm"))



if __name__ == "__main__":
        df = pd.read_csv("input.csv")
        
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        execute_state = app.exec_()
        df.to_csv(f"output_csv/output_{datetime.now()}.csv")
        sys.exit(execute_state)
